from .inline import (  # noqa: F401
    MENU_INLINE_KEYBOARD,
    START_INLINE_KEYBOARD,
    PROFILE_INLINE_KEYBOARD,
    GENDER_INLINE_KEYBOARD,
    OPEN_MENU_INLINE_KEYBOARD,
    CALCULATE_FINISH_INLINE_KEYBOARD,
    LANGUAGE_INLINE_KEYBOARD,
    UNIT_INLINE_KEYBOARD,
    SETTINGS_END_INLINE_KEYBOARD,
    get_keyboard_of_nums,
    get_yesno_keyboard,
    get_timezone_keyboard,
)
